// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request_info.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_request_5finfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_request_5finfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/wrappers.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_request_5finfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_request_5finfo_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_request_5finfo_2eproto;
namespace wasm {
namespace common {
class RequestInfo;
class RequestInfoDefaultTypeInternal;
extern RequestInfoDefaultTypeInternal _RequestInfo_default_instance_;
}  // namespace common
}  // namespace wasm
PROTOBUF_NAMESPACE_OPEN
template<> ::wasm::common::RequestInfo* Arena::CreateMaybeMessage<::wasm::common::RequestInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace wasm {
namespace common {

// ===================================================================

class RequestInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wasm.common.RequestInfo) */ {
 public:
  RequestInfo();
  virtual ~RequestInfo();

  RequestInfo(const RequestInfo& from);
  RequestInfo(RequestInfo&& from) noexcept
    : RequestInfo() {
    *this = ::std::move(from);
  }

  inline RequestInfo& operator=(const RequestInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestInfo& operator=(RequestInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RequestInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RequestInfo* internal_default_instance() {
    return reinterpret_cast<const RequestInfo*>(
               &_RequestInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RequestInfo& a, RequestInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RequestInfo* New() const final {
    return CreateMaybeMessage<RequestInfo>(nullptr);
  }

  RequestInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RequestInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RequestInfo& from);
  void MergeFrom(const RequestInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wasm.common.RequestInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_request_5finfo_2eproto);
    return ::descriptor_table_request_5finfo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestTimestampFieldNumber = 1,
    kResponseTimestampFieldNumber = 2,
    kRequestSizeFieldNumber = 3,
    kResponseSizeFieldNumber = 4,
    kDestinationPortFieldNumber = 5,
    kSourceAddressFieldNumber = 6,
    kDestinationAddressFieldNumber = 7,
    kRequestProtocolFieldNumber = 8,
    kResponseCodeFieldNumber = 9,
    kResponseFlagFieldNumber = 10,
    kDestinationServiceHostFieldNumber = 11,
    kDestinationServiceNameFieldNumber = 12,
    kRequestOperationFieldNumber = 13,
    kMtlsFieldNumber = 14,
    kSourcePrincipalFieldNumber = 15,
    kDestinationPrincipalFieldNumber = 16,
    kRbacPermissivePolicyIdFieldNumber = 17,
    kRbacPermissiveEngineResultFieldNumber = 18,
    kDurationFieldNumber = 19,
    kResponseDurationFieldNumber = 20,
    kRequestedServerNameFieldNumber = 21,
    kTrafficDirectionFieldNumber = 22,
    kRefererFieldNumber = 23,
    kUserAgentFieldNumber = 24,
    kRequestIdFieldNumber = 25,
    kB3TraceIdFieldNumber = 26,
    kB3SpanIdFieldNumber = 27,
    kB3TraceSampledFieldNumber = 28,
    kUrlPathFieldNumber = 29,
    kUrlHostFieldNumber = 30,
    kUrlSchemeFieldNumber = 31,
  };
  // .google.protobuf.Int64Value request_timestamp = 1;
  bool has_request_timestamp() const;
  void clear_request_timestamp();
  const PROTOBUF_NAMESPACE_ID::Int64Value& request_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Int64Value* release_request_timestamp();
  PROTOBUF_NAMESPACE_ID::Int64Value* mutable_request_timestamp();
  void set_allocated_request_timestamp(PROTOBUF_NAMESPACE_ID::Int64Value* request_timestamp);

  // .google.protobuf.Int64Value response_timestamp = 2;
  bool has_response_timestamp() const;
  void clear_response_timestamp();
  const PROTOBUF_NAMESPACE_ID::Int64Value& response_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Int64Value* release_response_timestamp();
  PROTOBUF_NAMESPACE_ID::Int64Value* mutable_response_timestamp();
  void set_allocated_response_timestamp(PROTOBUF_NAMESPACE_ID::Int64Value* response_timestamp);

  // .google.protobuf.Int64Value request_size = 3;
  bool has_request_size() const;
  void clear_request_size();
  const PROTOBUF_NAMESPACE_ID::Int64Value& request_size() const;
  PROTOBUF_NAMESPACE_ID::Int64Value* release_request_size();
  PROTOBUF_NAMESPACE_ID::Int64Value* mutable_request_size();
  void set_allocated_request_size(PROTOBUF_NAMESPACE_ID::Int64Value* request_size);

  // .google.protobuf.Int64Value response_size = 4;
  bool has_response_size() const;
  void clear_response_size();
  const PROTOBUF_NAMESPACE_ID::Int64Value& response_size() const;
  PROTOBUF_NAMESPACE_ID::Int64Value* release_response_size();
  PROTOBUF_NAMESPACE_ID::Int64Value* mutable_response_size();
  void set_allocated_response_size(PROTOBUF_NAMESPACE_ID::Int64Value* response_size);

  // .google.protobuf.Int64Value destination_port = 5;
  bool has_destination_port() const;
  void clear_destination_port();
  const PROTOBUF_NAMESPACE_ID::Int64Value& destination_port() const;
  PROTOBUF_NAMESPACE_ID::Int64Value* release_destination_port();
  PROTOBUF_NAMESPACE_ID::Int64Value* mutable_destination_port();
  void set_allocated_destination_port(PROTOBUF_NAMESPACE_ID::Int64Value* destination_port);

  // .google.protobuf.StringValue source_address = 6;
  bool has_source_address() const;
  void clear_source_address();
  const PROTOBUF_NAMESPACE_ID::StringValue& source_address() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_source_address();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_source_address();
  void set_allocated_source_address(PROTOBUF_NAMESPACE_ID::StringValue* source_address);

  // .google.protobuf.StringValue destination_address = 7;
  bool has_destination_address() const;
  void clear_destination_address();
  const PROTOBUF_NAMESPACE_ID::StringValue& destination_address() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_destination_address();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_destination_address();
  void set_allocated_destination_address(PROTOBUF_NAMESPACE_ID::StringValue* destination_address);

  // .google.protobuf.StringValue request_protocol = 8;
  bool has_request_protocol() const;
  void clear_request_protocol();
  const PROTOBUF_NAMESPACE_ID::StringValue& request_protocol() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_request_protocol();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_request_protocol();
  void set_allocated_request_protocol(PROTOBUF_NAMESPACE_ID::StringValue* request_protocol);

  // .google.protobuf.Int64Value response_code = 9;
  bool has_response_code() const;
  void clear_response_code();
  const PROTOBUF_NAMESPACE_ID::Int64Value& response_code() const;
  PROTOBUF_NAMESPACE_ID::Int64Value* release_response_code();
  PROTOBUF_NAMESPACE_ID::Int64Value* mutable_response_code();
  void set_allocated_response_code(PROTOBUF_NAMESPACE_ID::Int64Value* response_code);

  // .google.protobuf.StringValue response_flag = 10;
  bool has_response_flag() const;
  void clear_response_flag();
  const PROTOBUF_NAMESPACE_ID::StringValue& response_flag() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_response_flag();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_response_flag();
  void set_allocated_response_flag(PROTOBUF_NAMESPACE_ID::StringValue* response_flag);

  // .google.protobuf.StringValue destination_service_host = 11;
  bool has_destination_service_host() const;
  void clear_destination_service_host();
  const PROTOBUF_NAMESPACE_ID::StringValue& destination_service_host() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_destination_service_host();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_destination_service_host();
  void set_allocated_destination_service_host(PROTOBUF_NAMESPACE_ID::StringValue* destination_service_host);

  // .google.protobuf.StringValue destination_service_name = 12;
  bool has_destination_service_name() const;
  void clear_destination_service_name();
  const PROTOBUF_NAMESPACE_ID::StringValue& destination_service_name() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_destination_service_name();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_destination_service_name();
  void set_allocated_destination_service_name(PROTOBUF_NAMESPACE_ID::StringValue* destination_service_name);

  // .google.protobuf.StringValue request_operation = 13;
  bool has_request_operation() const;
  void clear_request_operation();
  const PROTOBUF_NAMESPACE_ID::StringValue& request_operation() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_request_operation();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_request_operation();
  void set_allocated_request_operation(PROTOBUF_NAMESPACE_ID::StringValue* request_operation);

  // .google.protobuf.BoolValue mtls = 14;
  bool has_mtls() const;
  void clear_mtls();
  const PROTOBUF_NAMESPACE_ID::BoolValue& mtls() const;
  PROTOBUF_NAMESPACE_ID::BoolValue* release_mtls();
  PROTOBUF_NAMESPACE_ID::BoolValue* mutable_mtls();
  void set_allocated_mtls(PROTOBUF_NAMESPACE_ID::BoolValue* mtls);

  // .google.protobuf.StringValue source_principal = 15;
  bool has_source_principal() const;
  void clear_source_principal();
  const PROTOBUF_NAMESPACE_ID::StringValue& source_principal() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_source_principal();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_source_principal();
  void set_allocated_source_principal(PROTOBUF_NAMESPACE_ID::StringValue* source_principal);

  // .google.protobuf.StringValue destination_principal = 16;
  bool has_destination_principal() const;
  void clear_destination_principal();
  const PROTOBUF_NAMESPACE_ID::StringValue& destination_principal() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_destination_principal();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_destination_principal();
  void set_allocated_destination_principal(PROTOBUF_NAMESPACE_ID::StringValue* destination_principal);

  // .google.protobuf.StringValue rbac_permissive_policy_id = 17;
  bool has_rbac_permissive_policy_id() const;
  void clear_rbac_permissive_policy_id();
  const PROTOBUF_NAMESPACE_ID::StringValue& rbac_permissive_policy_id() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_rbac_permissive_policy_id();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_rbac_permissive_policy_id();
  void set_allocated_rbac_permissive_policy_id(PROTOBUF_NAMESPACE_ID::StringValue* rbac_permissive_policy_id);

  // .google.protobuf.StringValue rbac_permissive_engine_result = 18;
  bool has_rbac_permissive_engine_result() const;
  void clear_rbac_permissive_engine_result();
  const PROTOBUF_NAMESPACE_ID::StringValue& rbac_permissive_engine_result() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_rbac_permissive_engine_result();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_rbac_permissive_engine_result();
  void set_allocated_rbac_permissive_engine_result(PROTOBUF_NAMESPACE_ID::StringValue* rbac_permissive_engine_result);

  // .google.protobuf.Int64Value duration = 19;
  bool has_duration() const;
  void clear_duration();
  const PROTOBUF_NAMESPACE_ID::Int64Value& duration() const;
  PROTOBUF_NAMESPACE_ID::Int64Value* release_duration();
  PROTOBUF_NAMESPACE_ID::Int64Value* mutable_duration();
  void set_allocated_duration(PROTOBUF_NAMESPACE_ID::Int64Value* duration);

  // .google.protobuf.Int64Value response_duration = 20;
  bool has_response_duration() const;
  void clear_response_duration();
  const PROTOBUF_NAMESPACE_ID::Int64Value& response_duration() const;
  PROTOBUF_NAMESPACE_ID::Int64Value* release_response_duration();
  PROTOBUF_NAMESPACE_ID::Int64Value* mutable_response_duration();
  void set_allocated_response_duration(PROTOBUF_NAMESPACE_ID::Int64Value* response_duration);

  // .google.protobuf.StringValue requested_server_name = 21;
  bool has_requested_server_name() const;
  void clear_requested_server_name();
  const PROTOBUF_NAMESPACE_ID::StringValue& requested_server_name() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_requested_server_name();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_requested_server_name();
  void set_allocated_requested_server_name(PROTOBUF_NAMESPACE_ID::StringValue* requested_server_name);

  // .google.protobuf.Int64Value traffic_direction = 22;
  bool has_traffic_direction() const;
  void clear_traffic_direction();
  const PROTOBUF_NAMESPACE_ID::Int64Value& traffic_direction() const;
  PROTOBUF_NAMESPACE_ID::Int64Value* release_traffic_direction();
  PROTOBUF_NAMESPACE_ID::Int64Value* mutable_traffic_direction();
  void set_allocated_traffic_direction(PROTOBUF_NAMESPACE_ID::Int64Value* traffic_direction);

  // .google.protobuf.StringValue referer = 23;
  bool has_referer() const;
  void clear_referer();
  const PROTOBUF_NAMESPACE_ID::StringValue& referer() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_referer();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_referer();
  void set_allocated_referer(PROTOBUF_NAMESPACE_ID::StringValue* referer);

  // .google.protobuf.StringValue user_agent = 24;
  bool has_user_agent() const;
  void clear_user_agent();
  const PROTOBUF_NAMESPACE_ID::StringValue& user_agent() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_user_agent();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_user_agent();
  void set_allocated_user_agent(PROTOBUF_NAMESPACE_ID::StringValue* user_agent);

  // .google.protobuf.StringValue request_id = 25;
  bool has_request_id() const;
  void clear_request_id();
  const PROTOBUF_NAMESPACE_ID::StringValue& request_id() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_request_id();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_request_id();
  void set_allocated_request_id(PROTOBUF_NAMESPACE_ID::StringValue* request_id);

  // .google.protobuf.StringValue b3_trace_id = 26;
  bool has_b3_trace_id() const;
  void clear_b3_trace_id();
  const PROTOBUF_NAMESPACE_ID::StringValue& b3_trace_id() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_b3_trace_id();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_b3_trace_id();
  void set_allocated_b3_trace_id(PROTOBUF_NAMESPACE_ID::StringValue* b3_trace_id);

  // .google.protobuf.StringValue b3_span_id = 27;
  bool has_b3_span_id() const;
  void clear_b3_span_id();
  const PROTOBUF_NAMESPACE_ID::StringValue& b3_span_id() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_b3_span_id();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_b3_span_id();
  void set_allocated_b3_span_id(PROTOBUF_NAMESPACE_ID::StringValue* b3_span_id);

  // .google.protobuf.BoolValue b3_trace_sampled = 28;
  bool has_b3_trace_sampled() const;
  void clear_b3_trace_sampled();
  const PROTOBUF_NAMESPACE_ID::BoolValue& b3_trace_sampled() const;
  PROTOBUF_NAMESPACE_ID::BoolValue* release_b3_trace_sampled();
  PROTOBUF_NAMESPACE_ID::BoolValue* mutable_b3_trace_sampled();
  void set_allocated_b3_trace_sampled(PROTOBUF_NAMESPACE_ID::BoolValue* b3_trace_sampled);

  // .google.protobuf.StringValue url_path = 29;
  bool has_url_path() const;
  void clear_url_path();
  const PROTOBUF_NAMESPACE_ID::StringValue& url_path() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_url_path();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_url_path();
  void set_allocated_url_path(PROTOBUF_NAMESPACE_ID::StringValue* url_path);

  // .google.protobuf.StringValue url_host = 30;
  bool has_url_host() const;
  void clear_url_host();
  const PROTOBUF_NAMESPACE_ID::StringValue& url_host() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_url_host();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_url_host();
  void set_allocated_url_host(PROTOBUF_NAMESPACE_ID::StringValue* url_host);

  // .google.protobuf.StringValue url_scheme = 31;
  bool has_url_scheme() const;
  void clear_url_scheme();
  const PROTOBUF_NAMESPACE_ID::StringValue& url_scheme() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_url_scheme();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_url_scheme();
  void set_allocated_url_scheme(PROTOBUF_NAMESPACE_ID::StringValue* url_scheme);

  // @@protoc_insertion_point(class_scope:wasm.common.RequestInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  PROTOBUF_NAMESPACE_ID::Int64Value* request_timestamp_;
  PROTOBUF_NAMESPACE_ID::Int64Value* response_timestamp_;
  PROTOBUF_NAMESPACE_ID::Int64Value* request_size_;
  PROTOBUF_NAMESPACE_ID::Int64Value* response_size_;
  PROTOBUF_NAMESPACE_ID::Int64Value* destination_port_;
  PROTOBUF_NAMESPACE_ID::StringValue* source_address_;
  PROTOBUF_NAMESPACE_ID::StringValue* destination_address_;
  PROTOBUF_NAMESPACE_ID::StringValue* request_protocol_;
  PROTOBUF_NAMESPACE_ID::Int64Value* response_code_;
  PROTOBUF_NAMESPACE_ID::StringValue* response_flag_;
  PROTOBUF_NAMESPACE_ID::StringValue* destination_service_host_;
  PROTOBUF_NAMESPACE_ID::StringValue* destination_service_name_;
  PROTOBUF_NAMESPACE_ID::StringValue* request_operation_;
  PROTOBUF_NAMESPACE_ID::BoolValue* mtls_;
  PROTOBUF_NAMESPACE_ID::StringValue* source_principal_;
  PROTOBUF_NAMESPACE_ID::StringValue* destination_principal_;
  PROTOBUF_NAMESPACE_ID::StringValue* rbac_permissive_policy_id_;
  PROTOBUF_NAMESPACE_ID::StringValue* rbac_permissive_engine_result_;
  PROTOBUF_NAMESPACE_ID::Int64Value* duration_;
  PROTOBUF_NAMESPACE_ID::Int64Value* response_duration_;
  PROTOBUF_NAMESPACE_ID::StringValue* requested_server_name_;
  PROTOBUF_NAMESPACE_ID::Int64Value* traffic_direction_;
  PROTOBUF_NAMESPACE_ID::StringValue* referer_;
  PROTOBUF_NAMESPACE_ID::StringValue* user_agent_;
  PROTOBUF_NAMESPACE_ID::StringValue* request_id_;
  PROTOBUF_NAMESPACE_ID::StringValue* b3_trace_id_;
  PROTOBUF_NAMESPACE_ID::StringValue* b3_span_id_;
  PROTOBUF_NAMESPACE_ID::BoolValue* b3_trace_sampled_;
  PROTOBUF_NAMESPACE_ID::StringValue* url_path_;
  PROTOBUF_NAMESPACE_ID::StringValue* url_host_;
  PROTOBUF_NAMESPACE_ID::StringValue* url_scheme_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_request_5finfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RequestInfo

// .google.protobuf.Int64Value request_timestamp = 1;
inline bool RequestInfo::has_request_timestamp() const {
  return this != internal_default_instance() && request_timestamp_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::Int64Value& RequestInfo::request_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Int64Value* p = request_timestamp_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.request_timestamp)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Int64Value*>(
      &PROTOBUF_NAMESPACE_ID::_Int64Value_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::release_request_timestamp() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.request_timestamp)
  
  PROTOBUF_NAMESPACE_ID::Int64Value* temp = request_timestamp_;
  request_timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::mutable_request_timestamp() {
  
  if (request_timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Int64Value>(GetArenaNoVirtual());
    request_timestamp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.request_timestamp)
  return request_timestamp_;
}
inline void RequestInfo::set_allocated_request_timestamp(PROTOBUF_NAMESPACE_ID::Int64Value* request_timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_timestamp_);
  }
  if (request_timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      request_timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, request_timestamp, submessage_arena);
    }
    
  } else {
    
  }
  request_timestamp_ = request_timestamp;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.request_timestamp)
}

// .google.protobuf.Int64Value response_timestamp = 2;
inline bool RequestInfo::has_response_timestamp() const {
  return this != internal_default_instance() && response_timestamp_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::Int64Value& RequestInfo::response_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Int64Value* p = response_timestamp_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.response_timestamp)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Int64Value*>(
      &PROTOBUF_NAMESPACE_ID::_Int64Value_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::release_response_timestamp() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.response_timestamp)
  
  PROTOBUF_NAMESPACE_ID::Int64Value* temp = response_timestamp_;
  response_timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::mutable_response_timestamp() {
  
  if (response_timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Int64Value>(GetArenaNoVirtual());
    response_timestamp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.response_timestamp)
  return response_timestamp_;
}
inline void RequestInfo::set_allocated_response_timestamp(PROTOBUF_NAMESPACE_ID::Int64Value* response_timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_timestamp_);
  }
  if (response_timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      response_timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, response_timestamp, submessage_arena);
    }
    
  } else {
    
  }
  response_timestamp_ = response_timestamp;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.response_timestamp)
}

// .google.protobuf.Int64Value request_size = 3;
inline bool RequestInfo::has_request_size() const {
  return this != internal_default_instance() && request_size_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::Int64Value& RequestInfo::request_size() const {
  const PROTOBUF_NAMESPACE_ID::Int64Value* p = request_size_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.request_size)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Int64Value*>(
      &PROTOBUF_NAMESPACE_ID::_Int64Value_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::release_request_size() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.request_size)
  
  PROTOBUF_NAMESPACE_ID::Int64Value* temp = request_size_;
  request_size_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::mutable_request_size() {
  
  if (request_size_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Int64Value>(GetArenaNoVirtual());
    request_size_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.request_size)
  return request_size_;
}
inline void RequestInfo::set_allocated_request_size(PROTOBUF_NAMESPACE_ID::Int64Value* request_size) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_size_);
  }
  if (request_size) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_size)->GetArena();
    if (message_arena != submessage_arena) {
      request_size = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, request_size, submessage_arena);
    }
    
  } else {
    
  }
  request_size_ = request_size;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.request_size)
}

// .google.protobuf.Int64Value response_size = 4;
inline bool RequestInfo::has_response_size() const {
  return this != internal_default_instance() && response_size_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::Int64Value& RequestInfo::response_size() const {
  const PROTOBUF_NAMESPACE_ID::Int64Value* p = response_size_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.response_size)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Int64Value*>(
      &PROTOBUF_NAMESPACE_ID::_Int64Value_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::release_response_size() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.response_size)
  
  PROTOBUF_NAMESPACE_ID::Int64Value* temp = response_size_;
  response_size_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::mutable_response_size() {
  
  if (response_size_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Int64Value>(GetArenaNoVirtual());
    response_size_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.response_size)
  return response_size_;
}
inline void RequestInfo::set_allocated_response_size(PROTOBUF_NAMESPACE_ID::Int64Value* response_size) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_size_);
  }
  if (response_size) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_size)->GetArena();
    if (message_arena != submessage_arena) {
      response_size = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, response_size, submessage_arena);
    }
    
  } else {
    
  }
  response_size_ = response_size;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.response_size)
}

// .google.protobuf.Int64Value destination_port = 5;
inline bool RequestInfo::has_destination_port() const {
  return this != internal_default_instance() && destination_port_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::Int64Value& RequestInfo::destination_port() const {
  const PROTOBUF_NAMESPACE_ID::Int64Value* p = destination_port_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.destination_port)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Int64Value*>(
      &PROTOBUF_NAMESPACE_ID::_Int64Value_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::release_destination_port() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.destination_port)
  
  PROTOBUF_NAMESPACE_ID::Int64Value* temp = destination_port_;
  destination_port_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::mutable_destination_port() {
  
  if (destination_port_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Int64Value>(GetArenaNoVirtual());
    destination_port_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.destination_port)
  return destination_port_;
}
inline void RequestInfo::set_allocated_destination_port(PROTOBUF_NAMESPACE_ID::Int64Value* destination_port) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(destination_port_);
  }
  if (destination_port) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(destination_port)->GetArena();
    if (message_arena != submessage_arena) {
      destination_port = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, destination_port, submessage_arena);
    }
    
  } else {
    
  }
  destination_port_ = destination_port;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.destination_port)
}

// .google.protobuf.StringValue source_address = 6;
inline bool RequestInfo::has_source_address() const {
  return this != internal_default_instance() && source_address_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::source_address() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = source_address_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.source_address)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_source_address() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.source_address)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = source_address_;
  source_address_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_source_address() {
  
  if (source_address_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    source_address_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.source_address)
  return source_address_;
}
inline void RequestInfo::set_allocated_source_address(PROTOBUF_NAMESPACE_ID::StringValue* source_address) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(source_address_);
  }
  if (source_address) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(source_address)->GetArena();
    if (message_arena != submessage_arena) {
      source_address = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, source_address, submessage_arena);
    }
    
  } else {
    
  }
  source_address_ = source_address;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.source_address)
}

// .google.protobuf.StringValue destination_address = 7;
inline bool RequestInfo::has_destination_address() const {
  return this != internal_default_instance() && destination_address_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::destination_address() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = destination_address_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.destination_address)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_destination_address() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.destination_address)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = destination_address_;
  destination_address_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_destination_address() {
  
  if (destination_address_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    destination_address_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.destination_address)
  return destination_address_;
}
inline void RequestInfo::set_allocated_destination_address(PROTOBUF_NAMESPACE_ID::StringValue* destination_address) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(destination_address_);
  }
  if (destination_address) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(destination_address)->GetArena();
    if (message_arena != submessage_arena) {
      destination_address = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, destination_address, submessage_arena);
    }
    
  } else {
    
  }
  destination_address_ = destination_address;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.destination_address)
}

// .google.protobuf.StringValue request_protocol = 8;
inline bool RequestInfo::has_request_protocol() const {
  return this != internal_default_instance() && request_protocol_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::request_protocol() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = request_protocol_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.request_protocol)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_request_protocol() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.request_protocol)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = request_protocol_;
  request_protocol_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_request_protocol() {
  
  if (request_protocol_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    request_protocol_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.request_protocol)
  return request_protocol_;
}
inline void RequestInfo::set_allocated_request_protocol(PROTOBUF_NAMESPACE_ID::StringValue* request_protocol) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_protocol_);
  }
  if (request_protocol) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_protocol)->GetArena();
    if (message_arena != submessage_arena) {
      request_protocol = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, request_protocol, submessage_arena);
    }
    
  } else {
    
  }
  request_protocol_ = request_protocol;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.request_protocol)
}

// .google.protobuf.Int64Value response_code = 9;
inline bool RequestInfo::has_response_code() const {
  return this != internal_default_instance() && response_code_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::Int64Value& RequestInfo::response_code() const {
  const PROTOBUF_NAMESPACE_ID::Int64Value* p = response_code_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.response_code)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Int64Value*>(
      &PROTOBUF_NAMESPACE_ID::_Int64Value_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::release_response_code() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.response_code)
  
  PROTOBUF_NAMESPACE_ID::Int64Value* temp = response_code_;
  response_code_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::mutable_response_code() {
  
  if (response_code_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Int64Value>(GetArenaNoVirtual());
    response_code_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.response_code)
  return response_code_;
}
inline void RequestInfo::set_allocated_response_code(PROTOBUF_NAMESPACE_ID::Int64Value* response_code) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_code_);
  }
  if (response_code) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_code)->GetArena();
    if (message_arena != submessage_arena) {
      response_code = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, response_code, submessage_arena);
    }
    
  } else {
    
  }
  response_code_ = response_code;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.response_code)
}

// .google.protobuf.StringValue response_flag = 10;
inline bool RequestInfo::has_response_flag() const {
  return this != internal_default_instance() && response_flag_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::response_flag() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = response_flag_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.response_flag)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_response_flag() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.response_flag)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = response_flag_;
  response_flag_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_response_flag() {
  
  if (response_flag_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    response_flag_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.response_flag)
  return response_flag_;
}
inline void RequestInfo::set_allocated_response_flag(PROTOBUF_NAMESPACE_ID::StringValue* response_flag) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_flag_);
  }
  if (response_flag) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_flag)->GetArena();
    if (message_arena != submessage_arena) {
      response_flag = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, response_flag, submessage_arena);
    }
    
  } else {
    
  }
  response_flag_ = response_flag;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.response_flag)
}

// .google.protobuf.StringValue destination_service_host = 11;
inline bool RequestInfo::has_destination_service_host() const {
  return this != internal_default_instance() && destination_service_host_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::destination_service_host() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = destination_service_host_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.destination_service_host)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_destination_service_host() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.destination_service_host)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = destination_service_host_;
  destination_service_host_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_destination_service_host() {
  
  if (destination_service_host_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    destination_service_host_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.destination_service_host)
  return destination_service_host_;
}
inline void RequestInfo::set_allocated_destination_service_host(PROTOBUF_NAMESPACE_ID::StringValue* destination_service_host) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(destination_service_host_);
  }
  if (destination_service_host) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(destination_service_host)->GetArena();
    if (message_arena != submessage_arena) {
      destination_service_host = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, destination_service_host, submessage_arena);
    }
    
  } else {
    
  }
  destination_service_host_ = destination_service_host;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.destination_service_host)
}

// .google.protobuf.StringValue destination_service_name = 12;
inline bool RequestInfo::has_destination_service_name() const {
  return this != internal_default_instance() && destination_service_name_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::destination_service_name() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = destination_service_name_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.destination_service_name)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_destination_service_name() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.destination_service_name)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = destination_service_name_;
  destination_service_name_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_destination_service_name() {
  
  if (destination_service_name_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    destination_service_name_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.destination_service_name)
  return destination_service_name_;
}
inline void RequestInfo::set_allocated_destination_service_name(PROTOBUF_NAMESPACE_ID::StringValue* destination_service_name) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(destination_service_name_);
  }
  if (destination_service_name) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(destination_service_name)->GetArena();
    if (message_arena != submessage_arena) {
      destination_service_name = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, destination_service_name, submessage_arena);
    }
    
  } else {
    
  }
  destination_service_name_ = destination_service_name;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.destination_service_name)
}

// .google.protobuf.StringValue request_operation = 13;
inline bool RequestInfo::has_request_operation() const {
  return this != internal_default_instance() && request_operation_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::request_operation() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = request_operation_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.request_operation)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_request_operation() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.request_operation)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = request_operation_;
  request_operation_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_request_operation() {
  
  if (request_operation_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    request_operation_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.request_operation)
  return request_operation_;
}
inline void RequestInfo::set_allocated_request_operation(PROTOBUF_NAMESPACE_ID::StringValue* request_operation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_operation_);
  }
  if (request_operation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_operation)->GetArena();
    if (message_arena != submessage_arena) {
      request_operation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, request_operation, submessage_arena);
    }
    
  } else {
    
  }
  request_operation_ = request_operation;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.request_operation)
}

// .google.protobuf.BoolValue mtls = 14;
inline bool RequestInfo::has_mtls() const {
  return this != internal_default_instance() && mtls_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::BoolValue& RequestInfo::mtls() const {
  const PROTOBUF_NAMESPACE_ID::BoolValue* p = mtls_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.mtls)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::BoolValue*>(
      &PROTOBUF_NAMESPACE_ID::_BoolValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::BoolValue* RequestInfo::release_mtls() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.mtls)
  
  PROTOBUF_NAMESPACE_ID::BoolValue* temp = mtls_;
  mtls_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::BoolValue* RequestInfo::mutable_mtls() {
  
  if (mtls_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::BoolValue>(GetArenaNoVirtual());
    mtls_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.mtls)
  return mtls_;
}
inline void RequestInfo::set_allocated_mtls(PROTOBUF_NAMESPACE_ID::BoolValue* mtls) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(mtls_);
  }
  if (mtls) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(mtls)->GetArena();
    if (message_arena != submessage_arena) {
      mtls = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, mtls, submessage_arena);
    }
    
  } else {
    
  }
  mtls_ = mtls;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.mtls)
}

// .google.protobuf.StringValue source_principal = 15;
inline bool RequestInfo::has_source_principal() const {
  return this != internal_default_instance() && source_principal_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::source_principal() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = source_principal_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.source_principal)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_source_principal() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.source_principal)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = source_principal_;
  source_principal_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_source_principal() {
  
  if (source_principal_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    source_principal_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.source_principal)
  return source_principal_;
}
inline void RequestInfo::set_allocated_source_principal(PROTOBUF_NAMESPACE_ID::StringValue* source_principal) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(source_principal_);
  }
  if (source_principal) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(source_principal)->GetArena();
    if (message_arena != submessage_arena) {
      source_principal = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, source_principal, submessage_arena);
    }
    
  } else {
    
  }
  source_principal_ = source_principal;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.source_principal)
}

// .google.protobuf.StringValue destination_principal = 16;
inline bool RequestInfo::has_destination_principal() const {
  return this != internal_default_instance() && destination_principal_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::destination_principal() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = destination_principal_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.destination_principal)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_destination_principal() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.destination_principal)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = destination_principal_;
  destination_principal_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_destination_principal() {
  
  if (destination_principal_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    destination_principal_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.destination_principal)
  return destination_principal_;
}
inline void RequestInfo::set_allocated_destination_principal(PROTOBUF_NAMESPACE_ID::StringValue* destination_principal) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(destination_principal_);
  }
  if (destination_principal) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(destination_principal)->GetArena();
    if (message_arena != submessage_arena) {
      destination_principal = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, destination_principal, submessage_arena);
    }
    
  } else {
    
  }
  destination_principal_ = destination_principal;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.destination_principal)
}

// .google.protobuf.StringValue rbac_permissive_policy_id = 17;
inline bool RequestInfo::has_rbac_permissive_policy_id() const {
  return this != internal_default_instance() && rbac_permissive_policy_id_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::rbac_permissive_policy_id() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = rbac_permissive_policy_id_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.rbac_permissive_policy_id)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_rbac_permissive_policy_id() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.rbac_permissive_policy_id)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = rbac_permissive_policy_id_;
  rbac_permissive_policy_id_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_rbac_permissive_policy_id() {
  
  if (rbac_permissive_policy_id_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    rbac_permissive_policy_id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.rbac_permissive_policy_id)
  return rbac_permissive_policy_id_;
}
inline void RequestInfo::set_allocated_rbac_permissive_policy_id(PROTOBUF_NAMESPACE_ID::StringValue* rbac_permissive_policy_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(rbac_permissive_policy_id_);
  }
  if (rbac_permissive_policy_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rbac_permissive_policy_id)->GetArena();
    if (message_arena != submessage_arena) {
      rbac_permissive_policy_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rbac_permissive_policy_id, submessage_arena);
    }
    
  } else {
    
  }
  rbac_permissive_policy_id_ = rbac_permissive_policy_id;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.rbac_permissive_policy_id)
}

// .google.protobuf.StringValue rbac_permissive_engine_result = 18;
inline bool RequestInfo::has_rbac_permissive_engine_result() const {
  return this != internal_default_instance() && rbac_permissive_engine_result_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::rbac_permissive_engine_result() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = rbac_permissive_engine_result_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.rbac_permissive_engine_result)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_rbac_permissive_engine_result() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.rbac_permissive_engine_result)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = rbac_permissive_engine_result_;
  rbac_permissive_engine_result_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_rbac_permissive_engine_result() {
  
  if (rbac_permissive_engine_result_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    rbac_permissive_engine_result_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.rbac_permissive_engine_result)
  return rbac_permissive_engine_result_;
}
inline void RequestInfo::set_allocated_rbac_permissive_engine_result(PROTOBUF_NAMESPACE_ID::StringValue* rbac_permissive_engine_result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(rbac_permissive_engine_result_);
  }
  if (rbac_permissive_engine_result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rbac_permissive_engine_result)->GetArena();
    if (message_arena != submessage_arena) {
      rbac_permissive_engine_result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rbac_permissive_engine_result, submessage_arena);
    }
    
  } else {
    
  }
  rbac_permissive_engine_result_ = rbac_permissive_engine_result;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.rbac_permissive_engine_result)
}

// .google.protobuf.Int64Value duration = 19;
inline bool RequestInfo::has_duration() const {
  return this != internal_default_instance() && duration_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::Int64Value& RequestInfo::duration() const {
  const PROTOBUF_NAMESPACE_ID::Int64Value* p = duration_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.duration)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Int64Value*>(
      &PROTOBUF_NAMESPACE_ID::_Int64Value_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::release_duration() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.duration)
  
  PROTOBUF_NAMESPACE_ID::Int64Value* temp = duration_;
  duration_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::mutable_duration() {
  
  if (duration_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Int64Value>(GetArenaNoVirtual());
    duration_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.duration)
  return duration_;
}
inline void RequestInfo::set_allocated_duration(PROTOBUF_NAMESPACE_ID::Int64Value* duration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(duration_);
  }
  if (duration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(duration)->GetArena();
    if (message_arena != submessage_arena) {
      duration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, duration, submessage_arena);
    }
    
  } else {
    
  }
  duration_ = duration;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.duration)
}

// .google.protobuf.Int64Value response_duration = 20;
inline bool RequestInfo::has_response_duration() const {
  return this != internal_default_instance() && response_duration_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::Int64Value& RequestInfo::response_duration() const {
  const PROTOBUF_NAMESPACE_ID::Int64Value* p = response_duration_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.response_duration)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Int64Value*>(
      &PROTOBUF_NAMESPACE_ID::_Int64Value_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::release_response_duration() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.response_duration)
  
  PROTOBUF_NAMESPACE_ID::Int64Value* temp = response_duration_;
  response_duration_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::mutable_response_duration() {
  
  if (response_duration_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Int64Value>(GetArenaNoVirtual());
    response_duration_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.response_duration)
  return response_duration_;
}
inline void RequestInfo::set_allocated_response_duration(PROTOBUF_NAMESPACE_ID::Int64Value* response_duration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_duration_);
  }
  if (response_duration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(response_duration)->GetArena();
    if (message_arena != submessage_arena) {
      response_duration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, response_duration, submessage_arena);
    }
    
  } else {
    
  }
  response_duration_ = response_duration;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.response_duration)
}

// .google.protobuf.StringValue requested_server_name = 21;
inline bool RequestInfo::has_requested_server_name() const {
  return this != internal_default_instance() && requested_server_name_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::requested_server_name() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = requested_server_name_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.requested_server_name)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_requested_server_name() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.requested_server_name)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = requested_server_name_;
  requested_server_name_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_requested_server_name() {
  
  if (requested_server_name_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    requested_server_name_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.requested_server_name)
  return requested_server_name_;
}
inline void RequestInfo::set_allocated_requested_server_name(PROTOBUF_NAMESPACE_ID::StringValue* requested_server_name) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(requested_server_name_);
  }
  if (requested_server_name) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(requested_server_name)->GetArena();
    if (message_arena != submessage_arena) {
      requested_server_name = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, requested_server_name, submessage_arena);
    }
    
  } else {
    
  }
  requested_server_name_ = requested_server_name;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.requested_server_name)
}

// .google.protobuf.Int64Value traffic_direction = 22;
inline bool RequestInfo::has_traffic_direction() const {
  return this != internal_default_instance() && traffic_direction_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::Int64Value& RequestInfo::traffic_direction() const {
  const PROTOBUF_NAMESPACE_ID::Int64Value* p = traffic_direction_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.traffic_direction)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Int64Value*>(
      &PROTOBUF_NAMESPACE_ID::_Int64Value_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::release_traffic_direction() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.traffic_direction)
  
  PROTOBUF_NAMESPACE_ID::Int64Value* temp = traffic_direction_;
  traffic_direction_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Int64Value* RequestInfo::mutable_traffic_direction() {
  
  if (traffic_direction_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Int64Value>(GetArenaNoVirtual());
    traffic_direction_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.traffic_direction)
  return traffic_direction_;
}
inline void RequestInfo::set_allocated_traffic_direction(PROTOBUF_NAMESPACE_ID::Int64Value* traffic_direction) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(traffic_direction_);
  }
  if (traffic_direction) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(traffic_direction)->GetArena();
    if (message_arena != submessage_arena) {
      traffic_direction = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, traffic_direction, submessage_arena);
    }
    
  } else {
    
  }
  traffic_direction_ = traffic_direction;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.traffic_direction)
}

// .google.protobuf.StringValue referer = 23;
inline bool RequestInfo::has_referer() const {
  return this != internal_default_instance() && referer_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::referer() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = referer_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.referer)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_referer() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.referer)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = referer_;
  referer_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_referer() {
  
  if (referer_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    referer_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.referer)
  return referer_;
}
inline void RequestInfo::set_allocated_referer(PROTOBUF_NAMESPACE_ID::StringValue* referer) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(referer_);
  }
  if (referer) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(referer)->GetArena();
    if (message_arena != submessage_arena) {
      referer = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, referer, submessage_arena);
    }
    
  } else {
    
  }
  referer_ = referer;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.referer)
}

// .google.protobuf.StringValue user_agent = 24;
inline bool RequestInfo::has_user_agent() const {
  return this != internal_default_instance() && user_agent_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::user_agent() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = user_agent_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.user_agent)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_user_agent() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.user_agent)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = user_agent_;
  user_agent_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_user_agent() {
  
  if (user_agent_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    user_agent_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.user_agent)
  return user_agent_;
}
inline void RequestInfo::set_allocated_user_agent(PROTOBUF_NAMESPACE_ID::StringValue* user_agent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_agent_);
  }
  if (user_agent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_agent)->GetArena();
    if (message_arena != submessage_arena) {
      user_agent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, user_agent, submessage_arena);
    }
    
  } else {
    
  }
  user_agent_ = user_agent;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.user_agent)
}

// .google.protobuf.StringValue request_id = 25;
inline bool RequestInfo::has_request_id() const {
  return this != internal_default_instance() && request_id_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::request_id() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = request_id_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.request_id)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_request_id() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.request_id)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = request_id_;
  request_id_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_request_id() {
  
  if (request_id_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    request_id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.request_id)
  return request_id_;
}
inline void RequestInfo::set_allocated_request_id(PROTOBUF_NAMESPACE_ID::StringValue* request_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_id_);
  }
  if (request_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(request_id)->GetArena();
    if (message_arena != submessage_arena) {
      request_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, request_id, submessage_arena);
    }
    
  } else {
    
  }
  request_id_ = request_id;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.request_id)
}

// .google.protobuf.StringValue b3_trace_id = 26;
inline bool RequestInfo::has_b3_trace_id() const {
  return this != internal_default_instance() && b3_trace_id_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::b3_trace_id() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = b3_trace_id_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.b3_trace_id)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_b3_trace_id() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.b3_trace_id)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = b3_trace_id_;
  b3_trace_id_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_b3_trace_id() {
  
  if (b3_trace_id_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    b3_trace_id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.b3_trace_id)
  return b3_trace_id_;
}
inline void RequestInfo::set_allocated_b3_trace_id(PROTOBUF_NAMESPACE_ID::StringValue* b3_trace_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(b3_trace_id_);
  }
  if (b3_trace_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(b3_trace_id)->GetArena();
    if (message_arena != submessage_arena) {
      b3_trace_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, b3_trace_id, submessage_arena);
    }
    
  } else {
    
  }
  b3_trace_id_ = b3_trace_id;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.b3_trace_id)
}

// .google.protobuf.StringValue b3_span_id = 27;
inline bool RequestInfo::has_b3_span_id() const {
  return this != internal_default_instance() && b3_span_id_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::b3_span_id() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = b3_span_id_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.b3_span_id)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_b3_span_id() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.b3_span_id)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = b3_span_id_;
  b3_span_id_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_b3_span_id() {
  
  if (b3_span_id_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    b3_span_id_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.b3_span_id)
  return b3_span_id_;
}
inline void RequestInfo::set_allocated_b3_span_id(PROTOBUF_NAMESPACE_ID::StringValue* b3_span_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(b3_span_id_);
  }
  if (b3_span_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(b3_span_id)->GetArena();
    if (message_arena != submessage_arena) {
      b3_span_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, b3_span_id, submessage_arena);
    }
    
  } else {
    
  }
  b3_span_id_ = b3_span_id;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.b3_span_id)
}

// .google.protobuf.BoolValue b3_trace_sampled = 28;
inline bool RequestInfo::has_b3_trace_sampled() const {
  return this != internal_default_instance() && b3_trace_sampled_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::BoolValue& RequestInfo::b3_trace_sampled() const {
  const PROTOBUF_NAMESPACE_ID::BoolValue* p = b3_trace_sampled_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.b3_trace_sampled)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::BoolValue*>(
      &PROTOBUF_NAMESPACE_ID::_BoolValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::BoolValue* RequestInfo::release_b3_trace_sampled() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.b3_trace_sampled)
  
  PROTOBUF_NAMESPACE_ID::BoolValue* temp = b3_trace_sampled_;
  b3_trace_sampled_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::BoolValue* RequestInfo::mutable_b3_trace_sampled() {
  
  if (b3_trace_sampled_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::BoolValue>(GetArenaNoVirtual());
    b3_trace_sampled_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.b3_trace_sampled)
  return b3_trace_sampled_;
}
inline void RequestInfo::set_allocated_b3_trace_sampled(PROTOBUF_NAMESPACE_ID::BoolValue* b3_trace_sampled) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(b3_trace_sampled_);
  }
  if (b3_trace_sampled) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(b3_trace_sampled)->GetArena();
    if (message_arena != submessage_arena) {
      b3_trace_sampled = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, b3_trace_sampled, submessage_arena);
    }
    
  } else {
    
  }
  b3_trace_sampled_ = b3_trace_sampled;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.b3_trace_sampled)
}

// .google.protobuf.StringValue url_path = 29;
inline bool RequestInfo::has_url_path() const {
  return this != internal_default_instance() && url_path_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::url_path() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = url_path_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.url_path)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_url_path() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.url_path)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = url_path_;
  url_path_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_url_path() {
  
  if (url_path_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    url_path_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.url_path)
  return url_path_;
}
inline void RequestInfo::set_allocated_url_path(PROTOBUF_NAMESPACE_ID::StringValue* url_path) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(url_path_);
  }
  if (url_path) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(url_path)->GetArena();
    if (message_arena != submessage_arena) {
      url_path = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, url_path, submessage_arena);
    }
    
  } else {
    
  }
  url_path_ = url_path;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.url_path)
}

// .google.protobuf.StringValue url_host = 30;
inline bool RequestInfo::has_url_host() const {
  return this != internal_default_instance() && url_host_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::url_host() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = url_host_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.url_host)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_url_host() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.url_host)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = url_host_;
  url_host_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_url_host() {
  
  if (url_host_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    url_host_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.url_host)
  return url_host_;
}
inline void RequestInfo::set_allocated_url_host(PROTOBUF_NAMESPACE_ID::StringValue* url_host) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(url_host_);
  }
  if (url_host) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(url_host)->GetArena();
    if (message_arena != submessage_arena) {
      url_host = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, url_host, submessage_arena);
    }
    
  } else {
    
  }
  url_host_ = url_host;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.url_host)
}

// .google.protobuf.StringValue url_scheme = 31;
inline bool RequestInfo::has_url_scheme() const {
  return this != internal_default_instance() && url_scheme_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& RequestInfo::url_scheme() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = url_scheme_;
  // @@protoc_insertion_point(field_get:wasm.common.RequestInfo.url_scheme)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::release_url_scheme() {
  // @@protoc_insertion_point(field_release:wasm.common.RequestInfo.url_scheme)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = url_scheme_;
  url_scheme_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* RequestInfo::mutable_url_scheme() {
  
  if (url_scheme_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    url_scheme_ = p;
  }
  // @@protoc_insertion_point(field_mutable:wasm.common.RequestInfo.url_scheme)
  return url_scheme_;
}
inline void RequestInfo::set_allocated_url_scheme(PROTOBUF_NAMESPACE_ID::StringValue* url_scheme) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(url_scheme_);
  }
  if (url_scheme) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(url_scheme)->GetArena();
    if (message_arena != submessage_arena) {
      url_scheme = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, url_scheme, submessage_arena);
    }
    
  } else {
    
  }
  url_scheme_ = url_scheme;
  // @@protoc_insertion_point(field_set_allocated:wasm.common.RequestInfo.url_scheme)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace wasm

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_request_5finfo_2eproto
